server {
    listen 80;
    server_name localhost;

    location /projeto-korp {
        proxy_pass http://app-go:8080/projeto-korp;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 404 "Rota nao encontrada no Proxy Reverso Nginx. \n";
    }
}
